### ISSUE TITLE
Path globs support

### ISSUE THREAD

**Issue by ghost** [chbrown/json-check#1]
Hello,
I'd like to ask you to implement support for specifying input files by globs. That would allow us to run `json-check` from build (e.g. npm) scripts in a portable (cross-platform) way. There is actually a lot of linters that accept globs already (they use [minimatch](https://www.npmjs.com/package/minimatch)).

**Comment by radek-holy** [comment]
OK, I don't need this any more (I'm going to use something like `find ... | xargs ...`). But maybe some one else does...

**Comment by chbrown** [comment]
I tried to keep this script simple and tending toward the unix philosophy of doing one fully specified job well, but nothing else (and in the spirit of simplicity I just replaced yargs with optimist, since yargs was overkill).

I understand the cross-platform portability concern, but maybe there's a better solution, like putting glob handling earlier in the pipeline. I've not worked with Windows and Node.js — can you use pipes in npm scripts in that case? If there were Node.js versions of `find` and `xargs`, could you install them and then have an npm script like `node-find . -name '*.json' | xargs json-check`?

I'm not entirely against incorporating [`glob`](https://github.com/isaacs/node-glob) functionality, but if there's a way to keep the modules modular, I think that would be preferable.

**Comment by ghost** [comment]
Yes, that's the thing. There is no Node.js version of `find` and `xargs`. There is [find-glob](https://www.npmjs.com/package/find-glob) which is not exactly an inplace replacement for `find` but it can be used in this case. But there is no `xargs` replacement. [xargs](https://www.npmjs.com/package/xargs) has no [command line interface](https://github.com/tarruda/node-xargs/issues/1) and it does not seem to be [maintained](https://github.com/tarruda/node-xargs/issues/1#issuecomment-168396409) and [xargh](https://www.npmjs.com/package/xargh) requires Perl as a dependency.

Anyway, I understand your reasons. I already have a script which behaves like `find ... | xargs ...` as a workaround until globs support is implemented into all the linters I use or until an `xargs` replacement is published. I just tried whether you'd be interested in implementing it since some other linters already do that and since it would make my build scripts shorter (more readable) but actually I have no problem if you close this (or leave it open for some time).

**Comment by chbrown** [comment]
I thought about this a little bit more and I'm gonna stick to my minimalist/unix-philosophy guns.

In my own limited work I can assume I'll have reasonable POSIX environments, but if you have any Node.js-only recipes for hacking a cross-platform solution to the `find ... | xargs ...` problem, I'd be happy to add them to the README.

**Comment by ghost** [comment]
Fair enough.

As far as my Git remembers, I ended up using something like this:

``` javascript
/*
 * Run a command on files.
 *
 * The script usage is:
 * <pre>
 * Usage: $0 [--lang &lt;language&gt;]... [--] &lt;command&gt; [&lt;arg&gt;]...
 *
 * Options:
 *   --lang   Select project files written in LANGUAGE in the current working
 *            subtree [choices: "json", "javascript", "markdown"]
 *   command  A name of the command
 *   arg      Initial arguments to the command
 * </pre>
 *
 * For each file specified by the <code>--lang</code> arguments, the command
 * line is built from the <code>command</code> argument, the <code>arg</code>
 * arguments and the file name. If the arguments to this script are invalid, if
 * the files cannot be listed, if the command execution fails or if the command
 * returns a non-zero status code, the script exits with a non-zero status code.
 */

var child = require("child_process");

var globby = require("globby");
var yargs = require("yargs");

/**
 * A mapping from file language to globs matching appropriate files.
 */
var languages = {
  javascript: ["{!(node_modules)/**/,}*.js"],
  json: ["{!(node_modules)/**/,}{,.}*.json", ".jshintrc", ".jslintrc", ".remarkrc"],
  markdown: ["AUTHORS", "CONTRIBUTING", "CONTRIBUTORS", "README"]
};

/**
 * Run a command on files.
 *
 * The command and the files specification is parsed from the command line
 * arguments passed to this script. For each file specified by the
 * <code>--lang</code> arguments, the command line is built from the
 * <code>command</code> argument, the <code>arg</code> arguments and the file
 * name. If the arguments to this script are invalid, if the files cannot be
 * listed, if the command execution fails or if the command returns a non-zero
 * status code, this process exits with a non-zero status code.
 */
function filesArgs() {
  "use strict";

  var options = yargs
      .usage("Usage: $0 [--lang <language>]... [--] <command> [<arg>]...")
      .option("lang", {
        choices: ["json", "javascript", "markdown"],
        describe: "Select project files written in LANGUAGE in the current working subtree",
        requiresArg: true,
        type: "string"
      })
      .demand(1)
      .argv;
  options.lang = options.lang ? [].concat(options.lang) : [];
  var patterns = Array.prototype.concat.apply([], Object.keys(languages)
      .filter(function (language) {
        return options.lang.indexOf(language) > -1;
      })
      .map(function (language) {
        return languages[language];
      })
  );

  globby(patterns).then(
      function (filenames) {
        var success = true;
        for (var index = 0; index < filenames.length; index++) {
          var result = child.spawnSync(options._[0], options._.slice(1).concat(filenames[index]), {stdio: [null, 1, 2]});

          if (result.error) {
            console.error(result.error);
            process.exit(1);
          }
          if (result.signal) {
            console.error("Killed by: %s", result.signal);
            process.exit(1);
          }
          if (result.status) {
            success = false;
          }
        }
        if (!success) {
          process.exit(1);
        }
      },
      function (reason) {
        console.error("Files cannot be listed: %s", reason);
        process.exit(1);
      }
  );
}

filesArgs();
```

But in case of `json-check`, it can be significantly simplified. At least, `json-check` allows passing multiple files at once. In that case, we can get rid of the loop and then use the asynchronous version of `child.spawnSync`. But it isn't tested very well since I decided later that the scripts running various linters should not be part of a project.
